// <auto-generated />
using System;
using DigitalSignage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalSignage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260222080050_RemoveLayoutCode")]
    partial class RemoveLayoutCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalSignage.Models.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailDomain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondaryColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CompanyID");

                    b.HasIndex("CompanyCode")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DigitalSignage.Models.CompanyConfiguration", b =>
                {
                    b.Property<int>("ConfigurationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationID"));

                    b.Property<bool>("AllowRecurringSchedules")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomCSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DefaultGridColumnsX")
                        .HasColumnType("int");

                    b.Property<int>("DefaultGridRowsY")
                        .HasColumnType("int");

                    b.Property<int>("DefaultScheduleDuration")
                        .HasColumnType("int");

                    b.Property<string>("DefaultSectionBorder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultSectionPadding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmailFrom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("EmailPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmailSmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("EmailSmtpServer")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailUsername")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EnableAdvancedScheduling")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAnalytics")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableAutoRotation")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableMediaUpload")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMediaSizeGB")
                        .HasColumnType("int");

                    b.Property<int>("MaxSchedulesPerPage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotificationEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("NotifyOnContentChange")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnError")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyOnScheduleChange")
                        .HasColumnType("bit");

                    b.Property<int>("ScreenRefreshInterval")
                        .HasColumnType("int");

                    b.HasKey("ConfigurationID");

                    b.HasIndex("CompanyID")
                        .IsUnique();

                    b.ToTable("CompanyConfigurations");
                });

            modelBuilder.Entity("DigitalSignage.Models.Content", b =>
                {
                    b.Property<int>("ContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentID"));

                    b.Property<string>("ContentData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MediaPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ContentID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DepartmentID", "CreatedDate");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("DigitalSignage.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DigitalSignage.Models.Layout", b =>
                {
                    b.Property<int>("LayoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LayoutID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LayoutDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LayoutID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("DigitalSignage.Models.LayoutSection", b =>
                {
                    b.Property<int>("LayoutSectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LayoutSectionID"));

                    b.Property<int>("ColumnIndex")
                        .HasColumnType("int");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LayoutID")
                        .HasColumnType("int");

                    b.Property<int>("RowIndex")
                        .HasColumnType("int");

                    b.Property<string>("SectionPosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LayoutSectionID");

                    b.HasIndex("LayoutID");

                    b.ToTable("LayoutSections");
                });

            modelBuilder.Entity("DigitalSignage.Models.Page", b =>
                {
                    b.Property<int>("PageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LayoutID")
                        .HasColumnType("int");

                    b.Property<string>("PageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PageTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PageID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("LayoutID");

                    b.HasIndex("PageCode")
                        .IsUnique();

                    b.HasIndex("PageName")
                        .IsUnique();

                    b.HasIndex("DepartmentID", "IsActive");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("DigitalSignage.Models.PageContent", b =>
                {
                    b.Property<int>("PageContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageContentID"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContentID")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DisplaySection")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.HasKey("PageContentID");

                    b.HasIndex("ContentID");

                    b.HasIndex("PageID");

                    b.ToTable("PageContents");
                });

            modelBuilder.Entity("DigitalSignage.Models.PageSection", b =>
                {
                    b.Property<int>("PageSectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageSectionID"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LayoutSectionID")
                        .HasColumnType("int");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.HasKey("PageSectionID");

                    b.HasIndex("LayoutSectionID");

                    b.HasIndex("PageID");

                    b.ToTable("PageSections");
                });

            modelBuilder.Entity("DigitalSignage.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("RecurrencePattern")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ScheduleID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("DepartmentID", "IsActive");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("DigitalSignage.Models.SchedulePage", b =>
                {
                    b.Property<int>("SchedulePageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchedulePageID"));

                    b.Property<int>("DisplayDuration")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PageID")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleID")
                        .HasColumnType("int");

                    b.HasKey("SchedulePageID");

                    b.HasIndex("PageID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("SchedulePages");
                });

            modelBuilder.Entity("DigitalSignage.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("AzureADObjectId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOffice365User")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalSignage.Models.UserCompanyRole", b =>
                {
                    b.Property<int>("UserCompanyRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCompanyRoleID"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserCompanyRoleID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("UserID", "CompanyID")
                        .IsUnique();

                    b.ToTable("UserCompanyRoles");
                });

            modelBuilder.Entity("DigitalSignage.Models.UserDepartmentRole", b =>
                {
                    b.Property<int>("UserDepartmentRoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDepartmentRoleID"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserDepartmentRoleID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("UserID", "DepartmentID")
                        .IsUnique();

                    b.ToTable("UserDepartmentRoles");
                });

            modelBuilder.Entity("DigitalSignage.Models.CompanyConfiguration", b =>
                {
                    b.HasOne("DigitalSignage.Models.Company", "Company")
                        .WithOne("Configuration")
                        .HasForeignKey("DigitalSignage.Models.CompanyConfiguration", "CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigitalSignage.Models.Content", b =>
                {
                    b.HasOne("DigitalSignage.Models.Department", "Department")
                        .WithMany("Contents")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DigitalSignage.Models.Department", b =>
                {
                    b.HasOne("DigitalSignage.Models.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigitalSignage.Models.Layout", b =>
                {
                    b.HasOne("DigitalSignage.Models.Company", "Company")
                        .WithMany("Layouts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DigitalSignage.Models.LayoutSection", b =>
                {
                    b.HasOne("DigitalSignage.Models.Layout", "Layout")
                        .WithMany("LayoutSections")
                        .HasForeignKey("LayoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("DigitalSignage.Models.Page", b =>
                {
                    b.HasOne("DigitalSignage.Models.Department", "Department")
                        .WithMany("Pages")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalSignage.Models.Layout", "Layout")
                        .WithMany("Pages")
                        .HasForeignKey("LayoutID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Layout");
                });

            modelBuilder.Entity("DigitalSignage.Models.PageContent", b =>
                {
                    b.HasOne("DigitalSignage.Models.Content", "Content")
                        .WithMany("PageContents")
                        .HasForeignKey("ContentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalSignage.Models.Page", "Page")
                        .WithMany("PageContents")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DigitalSignage.Models.PageSection", b =>
                {
                    b.HasOne("DigitalSignage.Models.LayoutSection", "LayoutSection")
                        .WithMany("PageSections")
                        .HasForeignKey("LayoutSectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DigitalSignage.Models.Page", "Page")
                        .WithMany("PageSections")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutSection");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("DigitalSignage.Models.Schedule", b =>
                {
                    b.HasOne("DigitalSignage.Models.Department", "Department")
                        .WithMany("Schedules")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DigitalSignage.Models.SchedulePage", b =>
                {
                    b.HasOne("DigitalSignage.Models.Page", "Page")
                        .WithMany("SchedulePages")
                        .HasForeignKey("PageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalSignage.Models.Schedule", "Schedule")
                        .WithMany("SchedulePages")
                        .HasForeignKey("ScheduleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DigitalSignage.Models.UserCompanyRole", b =>
                {
                    b.HasOne("DigitalSignage.Models.Company", "Company")
                        .WithMany("UserCompanyRoles")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalSignage.Models.User", "User")
                        .WithMany("UserCompanyRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalSignage.Models.UserDepartmentRole", b =>
                {
                    b.HasOne("DigitalSignage.Models.Department", "Department")
                        .WithMany("UserDepartmentRoles")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalSignage.Models.User", "User")
                        .WithMany("UserDepartmentRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalSignage.Models.Company", b =>
                {
                    b.Navigation("Configuration");

                    b.Navigation("Departments");

                    b.Navigation("Layouts");

                    b.Navigation("UserCompanyRoles");
                });

            modelBuilder.Entity("DigitalSignage.Models.Content", b =>
                {
                    b.Navigation("PageContents");
                });

            modelBuilder.Entity("DigitalSignage.Models.Department", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("Pages");

                    b.Navigation("Schedules");

                    b.Navigation("UserDepartmentRoles");
                });

            modelBuilder.Entity("DigitalSignage.Models.Layout", b =>
                {
                    b.Navigation("LayoutSections");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("DigitalSignage.Models.LayoutSection", b =>
                {
                    b.Navigation("PageSections");
                });

            modelBuilder.Entity("DigitalSignage.Models.Page", b =>
                {
                    b.Navigation("PageContents");

                    b.Navigation("PageSections");

                    b.Navigation("SchedulePages");
                });

            modelBuilder.Entity("DigitalSignage.Models.Schedule", b =>
                {
                    b.Navigation("SchedulePages");
                });

            modelBuilder.Entity("DigitalSignage.Models.User", b =>
                {
                    b.Navigation("UserCompanyRoles");

                    b.Navigation("UserDepartmentRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
